Algoritmo "Quantidade de latao"
Var
   // Seção de Declarações das variáveis
   latao,zinco,cobre:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("***")
   escreval("Informe a quantidade requirida de latão")
   leia(latao)

   cobre <- latao * 0.7
   zinco <- latao * 0.3
   
   escreval("A qtd de cobre é",cobre," e",zinco," de zinco para formar ",latao," de latão")

Fimalgoritmo