Algoritmo "13_ENTRE_1_100"
Var
i,n,total:inteiro
Inicio
escreval("***Quantidade de números entre 1 e 100***")
escreval("_________________________________________")
escreval("")
Escreval("Informe um número")
para i de 1 ate 20 faca
    leia(n)
    se(n >= 0 ) e (n <= 100)entao
         total<- total + 1
    fimse
fimpara
limpatela
escreval("A quantidade de números entre 1 e 100 são:",total)
Fimalgoritmo